# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bcf7ae603871ad386405b50526fcf82"
name = "import-customers"
handle = "import-customers"
application_url = "https://worst-shepherd-connectors-discussing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shortcode9904.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,read_customers"

[auth]
redirect_urls = [
  "https://worst-shepherd-connectors-discussing.trycloudflare.com/auth/callback",
  "https://worst-shepherd-connectors-discussing.trycloudflare.com/auth/shopify/callback",
  "https://worst-shepherd-connectors-discussing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
